CANONICAL_INTAKES = {

    "pp_regrind_medical": {
        "name": "PP Regrind Medical",
        "polymer": "PP",
        "form": "regrind",
        "color": "natural",
        "source_type": "post-industrial",
        "grade_hint": "homopolymer",
        "mfi_value": 10.0,
        "density_value": 0.9,
        "moisture_ppm": 200,
        "contamination_total_pct": 0.5,
        "has_metal": False,
        "has_fr": False,
        "has_residue": False,
        "filler_type": "none",
        "filler_pct": 0.0,
        "origin_application": "medical trays",
        "origin_sector": "medical",
        "origin_process_type": "injection",
        "quantity_per_load_lbs": 40000,
        "loads_per_month": 4,
        "deal_type": "ongoing",
    },

    "hdpe_drum_grind": {
        "name": "HDPE Drum Grind",
        "polymer": "HDPE",
        "form": "grind",
        "color": "mixed",
        "source_type": "post-consumer",
        "grade_hint": "",
        "mfi_value": 0.3,
        "density_value": 0.95,
        "moisture_ppm": 800,
        "contamination_total_pct": 2.0,
        "has_metal": True,
        "has_fr": False,
        "has_residue": True,
        "filler_type": "unknown",
        "filler_pct": 0.0,
        "origin_application": "chemical drums",
        "origin_sector": "industrial",
        "origin_process_type": "blow_molding",
        "quantity_per_load_lbs": 38000,
        "loads_per_month": 2,
        "deal_type": "spot",
    },

    "abs_fr_regrind": {
        "name": "ABS FR Regrind",
        "polymer": "ABS",
        "form": "regrind",
        "color": "black",
        "source_type": "post-industrial",
        "grade_hint": "FR grade",
        "mfi_value": 15,
        "density_value": 1.05,
        "moisture_ppm": 300,
        "contamination_total_pct": 1.0,
        "has_metal": False,
        "has_fr": True,
        "has_residue": False,
        "filler_type": "talc",
        "filler_pct": 10.0,
        "origin_application": "electronics housings",
        "origin_sector": "consumer_goods",
        "origin_process_type": "injection",
        "quantity_per_load_lbs": 42000,
        "loads_per_month": 3,
        "deal_type": "ongoing",
    },
}


